my_journalz/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :comments
  resources :posts
  resources :videos
  resources :photos
  resources :users do
    resource :profile do
      resources :posts
    end
  end
  

end

my_journalz/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :posts
end

my_journalz/app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :post
	# belongs_to :user
	# belongs_to :singular_word
	# has_many :plurarl_word
	# validates :flickr_id, :presence => true
end

my_journalz/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :profile
	has_many :photos
	has_many :videos

end

my_journalz/app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_many :posts 
end

my_journalz/app/models/user.rb
class User < ActiveRecord::Base

	has_one :profile, dependent: :destroy
	has_many :posts, through: :profile
	has_many :videos, through: :posts
	has_many :photos, through: :posts
	
	accepts_nested_attributes_for :profile

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 

end

my_journalz/app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	# validates :flickr_id, :presence => true
end

my_journalz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def after_sign_up_path_for(resource)
    new_user_profile_path # <- Path you want to redirect the user to.
  end

	def after_sign_in_path_for(resource)
  		if current_user.profile.nil?
   			new_user_profile_path(current_user)
  		else
  			user_profile_path(current_user)
  		end
  	end

  protect_from_forgery with: :exception
end

my_journalz/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

my_journalz/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
		@photos = Photo.all
	end

	def show
		
	end

	def new
		
	end

	def create

	end

	def edit

	end

	def destory

	end

end

my_journalz/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, :except => [:show, :index]

	def index
		@posts = current_user.profile.posts
	end

	def show
		@post = Post.find(params[:id])
		# then try to render the views/posts/show.html.erb
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@user = current_user
		# because a user has posts THROUGH profile, we have to say
		# yes, but in that case, a post would have to "belong_to" a user, instead of a profile
		# like you have here now is probably the best way
	    @post = current_user.profile.posts.new(post_params)
	    if @post.save
	      redirect_to user_profile_path(current_user)

	      # do you want to redirect back  to the profile page?
	      # takes you to post show
	    else 
	    	render :new
	    end
	end

	def update
	    @post = Post.find(params[:id])
	    if @post.update(post_params)
	      redirect_to @post
	    else
	      render 'edit'
	    end
	end

	def destroy
	    @post = Post.find(params[:id])
	    @post.destroy
	    redirect_to posts_path
	end

	private

	def post_params
    	params.require(:post).permit(:title, :body)
	end

end

my_journalz/app/controllers/profiles_controller.rb
require 'pry'
require 'httparty'

class ProfilesController < ApplicationController

	before_action :authenticate_user!, :except => [:show, :index]

	def index
		# @profile = current_user.build_profile()
		@posts = Post.all
	end

	def show
		@user = current_user
		@profile = current_user.profile
		@posts = current_user.profile.posts
		@post = Post.new

		# secret_key = ENV['secret_key']

    	# search_value = params[:search].gsub(/\s/,"%20")

    	# if search_value.present?
     #  		search_results = HTTParty.get("http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&rating=pg&tag=#{post.body}").parsed_response
     #  		@photos = search_results.first(100)
     #  		render :search
    	# else
     #  		redirect_to :back, notice: "Must provide a search term" 
    	# end
	
		# the view for this action needs to show the posts
	end

	def new
		@user = current_user
		@profile = current_user.profile.build

	end

	def create
 		@profile = current_user.profile.new(profile_params)
    	if @profile.save
	    	redirect_to user_profile_path
	    else
	     	render 'new'
	    end 
	end

	def edit
    	@profile = current_user.profile.find(params[:current_user])
	end

	def update
    	# @profile = current_user.profile.update_attributes(profile_params)
		@profile = current_user.profile.update_attributes(profile_params)
		if @profile.update(post_params)
      		redirect_to @profile
	    else
	     	render 'edit'
	    end
	end

	private

	def profile_params
    	params.require(:profile).permit(:name, :photo_url, :hometown, :interests, :about_me)
	end

end

my_journalz/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_user_profile_path(current_user)
  end

end

my_journalz/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]

  def index
    @users = User.all
  end

  def show

    @profile = current_user.profile
    # @profile = Profile.find_by(params[:current_user])
    # @profile = current_user.profile
  end

  def create
    # @profile = current_user.profile
    # @profile = current_user.profile.create!(name: params[:name], photo_url: params[:photo_url], hometown: params[:hometown], interests: params[:interests], about_me: params[:about_me])
  end

end

my_journalz/app/controllers/videos_controller.rb
class VideosController < ApplicationController
end

my_journalz/app/controllers/welcome_controller.rb
require 'pry'

class WelcomeController < ApplicationController

	before_action :authenticate_user!, :except => [:show, :index]

	def index
		
	end

end

my_journalz/app/helpers/application_helper.rb
module ApplicationHelper
end

my_journalz/app/helpers/comments_helper.rb
module CommentsHelper
end

my_journalz/app/helpers/photos_helper.rb
module PhotosHelper
end

my_journalz/app/helpers/posts_helper.rb
module PostsHelper
end

my_journalz/app/helpers/profiles_helper.rb
module ProfilesHelper
end

my_journalz/app/helpers/videos_helper.rb
module VideosHelper
end

my_journalz/app/views/posts/_form.html.erb
<%= form_for [current_user, @profile, @post], url: user_profile_posts_path(current_user, @profile, @post)  do |f| %>
  <p>
  	<%= f.label :title %><br>
  	<%= f.text_field :title %>
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.submit %>
    </p>
 <% end %>

my_journalz/app/views/posts/_new_giphy_post.html.erb
<!-- form, with inputs, hidden tag for post_type='giphy'  -->

<%= form_for(Post.new(post_type: 'giphy')) do |f| %>

  <%= f.label :title, "Post Title" %>
  <%= f.text_field :title %>
  <%= f.label :body, "Giphy Search Term" %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

my_journalz/app/views/posts/_post.html.erb
<div class="post">
  <h2 class="post-title"><%= post.title %></h2>
  <p class="post-body"><%= post.body %></p>
  <% if current_user %>
    <p class="post-author">By <%= profile.name %></p>
  <% end %>
  <p class="post-links">
    <%= link_to_unless_current 'View', post %>
    <% if can? :update, post %>
      | <%= link_to 'Edit', edit_post_path(post) %>
    <% end %>
    <% if can? :destroy, post %>
      | <%= link_to 'Delete', post, method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
  </p>
</div>

my_journalz/app/views/posts/index.html.erb
<h1>Posts</h1>
<%= link_to 'New Post', new_post_path %>
<%= render @posts %>

my_journalz/app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

my_journalz/app/views/profiles/_form.html.erb
<p>
<%= form_for new_user_profile_path, url: user_profile_path(current_user, @profile) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>
  <br><br>
  <%= f.label :hometown %>
  <%= f.text_field :hometown %>
  <br><br>
  <%= f.label :interests %>
  <%= f.text_field :interests %>
  <br><br>
  <%= f.label :about_me %>
  <%= f.text_field :about_me %>
  <br><br>
  <%= f.submit "Update" %>
<% end %>
</p>

my_journalz/app/views/profiles/edit.html.erb
<h2>Update Profile</h2>

<p>
<%= form_for @profile, url: {action: "update"} do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :photo_url %><br>
  <%= f.text_field :photo_url %>
  <br><br>
  <%= f.label :hometown %><br>
  <%= f.text_field :hometown %>
  <br><br>
  <%= f.label :interests %><br>
  <%= f.text_field :interests %>
  <br><br>
  <%= f.label :about_me %><br>
  <%= f.text_field :about_me %>
  <br><br>
  <%= f.submit "Update" %>
<% end %>
</p>

my_journalz/app/views/profiles/index.html.erb
<%= render "form" %>

<h2>User Profile</h2>
<a href="/users/<%= current_user.id %>/profile/<%= current_user.id %>/edit">Update Profile</a>

<h3>My Posts</h3>

my_journalz/app/views/profiles/new.html.erb
<h2> Make new Profile </h2>  

<%= render "form" %>

my_journalz/app/views/profiles/show.html.erb
<h2> Name: <%= current_user.profile.name %> </h2>
<h2> Interest: <%= current_user.profile.interests %></h2>
<h2> About me: <%= current_user.profile.about_me %></h2>

<div class="select-post">
	<h3>Select to create a post</h3>
	<select name="post-option">
	  <option value="">Please select</option>
	  <option value="text" selected="selected">Simple Text</option>
	  <option value="giphy">Giphy Slideshow</option>
	  <option value="3">Import Images</option>
	  <option value="4">Import Video</option>
	</select>
</div>

<%=render '/posts/form' %>
<%=render '/posts/new_giphy_post' %>

<%= form_for [@user, @profile, @post], url: user_profile_posts_path(@user, @post)  do |f| %>
  <p>
  	<%= f.label :title %><br>
  	<%= f.text_field :title %>
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<div class="post-content">
	<h1>Your Posts</h1>
	<% if @posts.any? %>
		<% @posts.each do |post| %>
			<div class= "post">
				<ul class= "post-ul">
				  <li><%= post.title %></li><br>
				  <li class= "post-body">
				  	<%= post.body %>
				    <% case post.post_type %>
					    <% when "text" %>
					      <%= post.body %>
					    <% when "giphy" %>
					      <%= image_tag("http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&rating=pg&tag=#{post.body}") %>
				     <% end %>

				   </li>
				</ul>
			</div>
		<% end %>
	<% end %>
</div>

<%= javascript_include_tag "profiles" %>

<script>
  $(document).ready( function(){
  	console.log("testing");
  	initializePostOptions();
  	showPostOption();
  })
</script>

my_journalz/app/views/users/index.html.erb
<ul>
  <% @places.each do |place| %>
    <li><%= link_to place.location, place_path(place) %></li>
  <% end %>
</ul>

my_journalz/app/views/welcome/index.html.erb
<h1>Welcome to My JournalZ </h1>

<% if current_user %>
  	<h2>User's ID</h2>
	<h2><%= current_user.id %></h2>
<% else %>
    <h2> Empty Page and please sign in</h2>
<% end %>